Add line height property for drop caps
danielgarthur/neanes pull request #83
Opened 2023-04-30 12:35 UTC by Nazaretto

Some of old slavic fonts (like Vilnius) have inconsistencies line height and font size, which in case of drop caps which causes some positioning problems. The easiest fix for that is to allow adjusting line height manually.

![Screen Shot 2023-04-30 at 15 33 56](https://user-images.githubusercontent.com/22745314/235353246-cee2f567-fe0f-4e53-b6fb-e161084c3f9c.jpg)

2023-05-01 15:38 UTC, danielgarthur commented
Congratulations on being our first contributor to make a pull request! In general the approach looks correct, I'll leave a few comments.

2023-05-01 15:49 UTC, danielgarthur commented
My general thoughts are 

- The dropcap element would have a `lineHeight` property that is a nullable number that represents the unitless number described [here](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height).
- If `lineHeight` is `null`, then the CSS should use `normal`. Or just omit the property in this case because the default value is `normal`.
- Use `InputUnit` with type `unitless` as the input, with an appropriate min, max, step size, and precision. This component does not current support blank values, but could be extended to have `nullable` prop that allows blank values.

2023-05-01 16:11 UTC, danielgarthur requested changes

2023-05-01 16:11 UTC, danielgarthur commented on src/models/save/v1/Element.ts
> +  public lineHeight: string = 'normal';
```suggestion
  public lineHeight: number | undefined = undefined;
```

2023-05-01 16:11 UTC, danielgarthur commented on src/models/save/v1/Element.ts
This file represents the model that is saved as JSON in the byz/byzx. Changes will also need to be made to `src/models/Element.ts`, which is the model used by the app.

2023-05-01 16:11 UTC, danielgarthur commented on src/models/save/v1/PageSetup.ts
> +  public dropCapDefaultLineHeight = 'normal';
See comments for `Element.ts`.

2023-05-01 16:11 UTC, danielgarthur commented on src/models/PageSetup.ts
> +  public dropCapDefaultLineHeight = 'normal';
```suggestion
  public dropCapDefaultLineHeight: number | null = null;
```

2023-05-01 16:11 UTC, danielgarthur commented on src/services/integration/ByzHtmlExporter.ts
> +        --byz-drop-cap-line-height: ${pageSetup.dropCapDefaultLineHeight};
```suggestion
```

There is no `--byz-drop-cap-line-height` in byzhtml. Instead, dropcaps always have `lineHeight: 0` and a vertical offset is applied. In Neanes, drop caps are positioned absolutely, and so line height does not affect the HTML flow. But byzhtml is built to allow drop caps to be used with any kind of positioning. The method `getDropCapAdjustment` should calculate the vertical offset correctly. This will need be tested, but since you already added the new line height property to the calculation, it will probably work.

2023-05-01 16:11 UTC, danielgarthur commented on src/services/SaveService.ts
> +    pageSetup.dropCapDefaultLineHeight = p.dropCapDefaultLineHeight;
```suggestion
    pageSetup.dropCapDefaultLineHeight = p.dropCapDefaultLineHeight ?? pageSetup.dropCapDefaultLineHeight;
```

It's best to fall back here to the default page setup line height to keep the existing code pattern.

2023-05-01 16:11 UTC, danielgarthur commented on src/components/ToolbarDropCap.vue
> +      <input
Use `InputUnit` with type unitless and all the appropriate props.

`InputUnit will need to be expanded to handle "blank" e.g. nullable values. If you need help with this part, let me know.

2023-05-01 16:11 UTC, danielgarthur commented on src/components/PageSetupDialog.vue
> +            <label class="drop-caps-label">Line height</label>
```suggestion
            <label class="drop-caps-label">Line Height</label>
```

For UI consistency, Height should be capitalized.

2023-05-01 16:11 UTC, danielgarthur commented on src/components/PageSetupDialog.vue
> +            <input
See comments about `InputUnit` in the toolbar file.

2023-05-12 23:05 UTC, Nazaretto commented
I've tried to implement `nullable` state for `InputUnit` with least changes possible, although I'm not familiar with all nuances of writing components with Vue, so if you have any suggestion, let me know.

2023-05-18 01:11 UTC, danielgarthur requested changes

2023-05-18 01:11 UTC, danielgarthur commented on src/models/PageSetup.ts
> +  public dropCapDefaultLineHeight: number | undefined = undefined;
The pattern for models is that the models in `save/` use `undefined` in order to prevent default values from being written out to the save file, which saves space. But the models used by the app use `null`.

Here it should be

```suggestion
  public dropCapDefaultLineHeight: number | null = null;
```

2023-05-18 01:11 UTC, danielgarthur commented on src/components/Editor.vue
> +  updateDropCapLineHeight(element: DropCapElement, lineHeight: number) {
```suggestion
  updateDropCapLineHeight(element: DropCapElement, lineHeight: number | null) {
```

2023-05-18 01:11 UTC, danielgarthur commented on src/components/PageSetupDialog.vue
> +              :nullable="true"
I think setting `precision` here would be good. I think 2 decimal places, enough, but I would be fine with 3 if you think it would be useful to display that many. Same goes for the toolbar.

2023-05-18 01:11 UTC, danielgarthur commented on src/components/ToolbarDropCap.vue
> +        placeholder="Line Height"
I think it might help to add a slash between the font size input and line height input, like ` [font size input] /  [line height input]`, and change the placeholder to the default value of `normal`. 

E.g.
 `[60      ]  /  [normal ]`
or
 `[60      ]  /  [1.4    ]`

2023-05-18 01:11 UTC, danielgarthur commented on src/components/InputUnit.vue
> +    if (convertedValue === null || convertedValue === undefined)
```suggestion
    if (convertedValue == null)
```

should work and would be consistent with the existing code style. `== null` checks for both `null` or `undefined` at the same time.

2023-05-18 01:11 UTC, danielgarthur commented on src/components/InputUnit.vue
> +      return this.nullable ? '' : '0';
The latest `master` branch now has a `default`  value that will need to be used here instead of 0. Try merging in latest `master`.

2023-05-18 01:11 UTC, danielgarthur commented on src/components/InputUnit.vue
> +    if (input === '' && this.nullable) {
```suggestion
    if (input.trim() === '' && this.nullable) {
```

Just to be safe. Someone might try to clear the input but accidentally leave a space.

2023-05-18 01:11 UTC, danielgarthur commented on src/models/save/v1/Element.ts
This still needs to be done.

2023-07-12 02:01 UTC, danielgarthur approved these changes

2023-07-12 02:08 UTC, merged